[package]
name = "solarfocus-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
rusqlite = { workspace = true }
env_logger = { workspace = true }
directories = { workspace = true }
rand = { workspace = true }
log = { workspace = true }
solar-focus-core = { path = "../../crates/core-domain" }

[[bin]]
name = "solarfocus-desktop"
path = "src/main.rs"
